package db

import (
	hd "beerwh/handlers"
)

func InitMeasures() {
	db = hd.Db
	db.Exec("INSERT INTO public.measures (id, name) VALUES (3, '01 colher de chá cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (9, '01 fatia fina')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (28, '1 posta ou filé')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (2, '01 bola')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (4, '01 colher de sopa cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (5, '01 colher de sopa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (6, '01 concha pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (7, '01 copo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (8, '01 escumadeira cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (10, '01 fatia pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (11, '01 fatia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (12, '01 metade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (13, '01 pedaço pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (14, '01 pegador')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (15, '01 porção pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (16, '01 potinho pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (17, '01 torrada')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (18, '01 unidade  pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (19, '01 unidade média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (21, '01 unidade pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (22, '01 unidade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (23, '1 e 1/2 xícara')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (24, '1 fatia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (26, '1 pedaço médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (27, '1 porção')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (29, '1 und')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (30, '1 unidade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (31, '1 xícara')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (32, '1/2 copo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (33, '1/2 unidade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (34, '1/2 xícara de chá')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (35, '1/2 xícara')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (36, '1/4 barra')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (37, '1/4 unidade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (38, '1/4 xícara de chá')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (39, '1/8 do pacote')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (40, '10 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (41, '17 unidades pequenos')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (42, '2 ¹/² fatia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (43, '2 colheres de copa cheias')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (44, '2 colheres de sopa cheias')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (45, '2 colheres de sopa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (46, '2 dentes')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (47, '2 discos de massa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (48, '2 fatias')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (49, '2 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (50, '2/3 xícara de chá')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (51, '3 colheres de sopa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (52, '3/4 de xícara')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (53, '3/4 xícara')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (54, '4 fatias')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (55, '4 unidades médias')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (56, '4 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (57, '6 colheres de sopa rasas')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (58, '6 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (59, 'bago  médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (60, 'barra pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (61, 'bife médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (62, 'bola grande')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (63, 'bola média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (64, 'bola')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (65, 'cacho pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (66, 'caixinha')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (67, 'cálice')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (68, 'colher (sopa) cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (69, 'colher de arroz cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (70, 'colher de chá')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (71, 'colher de servir')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (72, 'colher de sobremesa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (73, 'colher de sopa (molho)')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (74, 'colher de sopa cheia picada')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (75, 'colher de sopa cheia picado')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (76, 'colher de sopa cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (77, 'colher de sopa rasa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (78, 'colher de sopa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (79, 'colher do sopa cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (80, 'colher sopa (cheia)')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (81, 'colher sopa cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (82, 'colher sopa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (83, 'concha média cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (84, 'concha média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (85, 'concha pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (86, 'concha')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (87, 'copo de milk shake')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (88, 'copo descartável pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (89, 'copo duplo cheio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (90, 'copo duplo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (91, 'copo grande')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (92, 'copo pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (93, 'copo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (94, 'cuia média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (95, 'dose')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (96, 'escumadeira cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (97, 'escumadeira media cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (98, 'escumadeira')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (99, 'fatia grande')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (101, 'fatia média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (103, 'fatia pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (104, 'fatia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (105, 'folha média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (106, 'garrafa pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (107, 'garrafa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (108, 'garranha')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (109, 'gomo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (110, 'lata')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (113, 'média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (114, 'meia unidade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (115, 'pacote pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (116, 'pacote')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (117, 'pedaço grande')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (120, 'pedaço médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (121, 'pedaço pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (122, 'pegador')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (123, 'porção de 10 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (124, 'porção de 15cm')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (125, 'porção de 4 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (126, 'porção de 6 unidades')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (127, 'porção grande')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (128, 'porção média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (130, 'porção pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (132, 'porção')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (133, 'posta média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (134, 'posta pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (135, 'pote')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (136, 'prato')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (137, 'punhado')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (138, 'ramo médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (139, 'rodela média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (141, 'saco médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (142, 'sobrecoxa média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (143, 'sobrecoxa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (144, 'tablete')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (145, 'taça pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (146, 'taça')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (147, 'tulipa')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (148, 'um ovo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (149, 'unidade (inteira)')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (150, 'unidade aperitivo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (151, 'unidade comercial')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (152, 'unidade copo')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (153, 'unidade grande')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (155, 'unidade média')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (156, 'unidade pequena')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (157, 'unidade')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (158, 'xicara de café')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (25, '1 filé pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (111, 'filé médio')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (112, 'filé pequeno')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (159, 'xícara de café')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (160, 'xícara de chá cheia')")
	db.Exec("INSERT INTO public.measures (id, name) VALUES (161, 'xícara')")
	db.Exec("SELECT pg_catalog.setval('public.measures_id_seq', 165, true)")
}
